# Generated by Django 2.2 on 2019-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccess',
            name='add',
            field=models.BooleanField(default=False, verbose_name='Права на добавление'),
        ),
        migrations.AddField(
            model_name='groupaccess',
            name='execute',
            field=models.BooleanField(default=False, verbose_name='Права на выполнение'),
        ),
        migrations.AddField(
            model_name='groupaccess',
            name='update',
            field=models.BooleanField(default=False, verbose_name='Права на изменение'),
        ),
        migrations.AddField(
            model_name='personaccess',
            name='add',
            field=models.BooleanField(default=False, verbose_name='Права на добавление'),
        ),
        migrations.AddField(
            model_name='personaccess',
            name='execute',
            field=models.BooleanField(default=False, verbose_name='Права на выполнение'),
        ),
        migrations.AddField(
            model_name='personaccess',
            name='update',
            field=models.BooleanField(default=False, verbose_name='Права на изменение'),
        ),
    ]
