# Generated by Django 2.2 on 2019-05-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20190523_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaccess',
            old_name='add',
            new_name='add_access',
        ),
        migrations.RenameField(
            model_name='personaccess',
            old_name='execute',
            new_name='execute_access',
        ),
    ]
