# Generated by Django 2.2 on 2019-05-26 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('reestr', '0002_auto_20190525_1510'),
        ('users', '0001_initial'),
        ('access', '0003_auto_20190525_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.BooleanField(verbose_name='Групповой доступ')),
                ('reason_open', models.TextField(max_length=1000, verbose_name='Причина запроса')),
                ('check', models.BooleanField(verbose_name='Обработано')),
                ('accept', models.BooleanField(verbose_name='Открыть доступ')),
                ('reason_reject', models.TextField(verbose_name='Причина отклонение')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reestr.Criminals', verbose_name='Досье')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Запрашиваемая группа')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Запрашиваемый человек')),
            ],
            options={
                'verbose_name': 'Запрос на доступ',
                'verbose_name_plural': 'Запросы на доступ',
            },
        ),
    ]
