# Generated by Django 2.2 on 2019-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_requesttoopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttoopen',
            name='reason_reject',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонение'),
        ),
    ]
