# Generated by Django 2.2 on 2019-05-26 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_auto_20190526_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttoopen',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата запроса'),
            preserve_default=False,
        ),
    ]
