# Generated by Django 2.2 on 2019-05-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminals',
            name='confident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.TrustLevel', verbose_name='Уровень секретности'),
        ),
    ]
