# Generated by Django 2.2 on 2019-06-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190604_0002'),
        ('reestr', '0003_auto_20190531_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminals',
            name='consideration',
            field=models.BooleanField(default=False, verbose_name='На рассмотрение'),
        ),
        migrations.AddField(
            model_name='criminals',
            name='to_rev',
            field=models.BooleanField(default=False, verbose_name='Пересмотр'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000)),
                ('reviewed', models.BooleanField(verbose_name='Пересмотрено')),
                ('dosye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reestr.Criminals', verbose_name='Досье')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Проверил')),
            ],
        ),
    ]
