# Generated by Django 2.2 on 2019-05-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(max_length=200, verbose_name='Действие')),
                ('data', models.DateTimeField(verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудит входа и выхода',
                'verbose_name_plural': 'Аудит входа и выхода',
                'ordering': ['-data'],
            },
        ),
    ]
