# Generated by Django 2.2 on 2019-05-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(verbose_name='Дата и время')),
                ('object_id', models.CharField(max_length=40, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Объект')),
                ('action_flag', models.SmallIntegerField(verbose_name='Код действия')),
                ('message', models.TextField(null=True, verbose_name='Сообщение')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Номер контента')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Журнал регистрации действий пользователей',
                'ordering': ['-action_time'],
            },
        ),
    ]
