# Generated by Django 2.2 on 2019-05-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0003_userlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
    ]
