# Generated by Django 2.2 on 2019-05-31 15:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190531_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='message',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.get_default_message, verbose_name='Сообщение'),
        ),
    ]
