# Generated by Django 2.2 on 2019-06-03 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190603_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pass_change_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 6, 18, 2, 794693, tzinfo=utc), verbose_name='Время изменения пароля'),
        ),
    ]
